backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "images/posts" # Media files will be stored in the repo under src/assets/images/posts
public_folder: "/images/posts" # The src attribute for uploaded media will begin with assets/images/posts

collections:
  - name: "conjuntos" # Used in routes, e.g., /admin/collections/blog
    label: "Conjuntos de Datos" # Used in the UI
    folder: "src/conjuntos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Nombre del conjunto de datos" }
      - { name: "description", label: "Descripción", widget: "markdown" }
      - { name: "institucion", label: "Institución" }
      - { label: "Imagen de Ícono", name: "icono", widget: "image" }
      - {
          name: "estado",
          label: "Estado",
          widget: "select",
          options: ["Pendiente ", "Publicado"],
        }
      - { name: "justificacion", label: "Justificación" }
      - { name: "enlace", label: "Enlace" }
show_preview_links: true
